[project]
name = "devop-toolkit"
version = "0.1.0"
description = "a toolkit to perform devops thingy (,'')9"
authors = [{ name = "widnyana", email = "hi@damarseta.id" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["confluent-kafka>=2.6.2"]
